### ISSUE TITLE
Nether Cake: Spawning in Lava SkyFactory4

### ISSUE THREAD

**Issue by ImWry** [Mrbysco/TelePastries#1]
## Client Info
* Minecraft Version:1.12.2

* Forge Version: 14.23.5.2831
* Mod Version: 4.0.2
* Java Version: 

##Spawning in Lava in SkyFactory4

So I crafted and placed down the Nether Cake, hit Right-Click, and got teleported to Nether.
Only problem is, I was completely surrounded by Lava.

I could figure out, what the problem might be. My platform (also the cake) is below Y=20, and the lava in the Nether is at Y=20. Is there a way to set the Nether further down?

I actually wanted to have my platform on a specific low Level, because of the Hostile Mobs are spawning more frequently... (Mob Farm).

Thanks for further replies

**Comment by Mrbysco** [comment]
Could you hand me your world seed?

**Comment by ImWry** [comment]
how can i pm you?

**Comment by Mrbysco** [comment]
You could join my discord. it's stated on the CurseForge page https://minecraft.curseforge.com/projects/more-cauldrons

**Comment by HawkDevelopment** [comment]
Issue still happens on 1.12.2
