### ISSUE TITLE
Add possibility to add custom cake from scratch (for pack devs)

### ISSUE THREAD

**Issue by NeutronSelector** [Mrbysco/TelePastries#13]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Hello, 

Actuellement un seul gâteau personnalisé peut être configuré pour une seul dimension. Ce serai génial si nous pouvions créer X gâteaux personnalisés avec json data-pack ou quelque chose comme ça. 

Thank's

**Comment by Mrbysco** [comment]
Please recreate this issue in English please
