### ISSUE TITLE
Stuck on Roof of Nether

### ISSUE THREAD

**Issue by VallenFrostweaver** [Mrbysco/TelePastries#2]
## Client Info
* Minecraft Version: 1.12.2
* Forge Version: 14.23.5.2831
* Mod Version: 0.3.3
* Java Version: 8 update 211
* SkyFactory 4 modpack: 4.0.2 & 4.0.3

## Issue Description
Using another mod item (that teleports you) one of my players (I am a server admin) teleported above the nether roof (acident? I don't know). They used the overworld cake they had to get back home but each time they return to the nether they are back above the nether.

## Reproduce Steps
1. Be above nether bedrock.
2. Use overworld cake to get to overworld.
3. Use Nether cake to get to nether.
4. Stuck. Can't reset spawn of nether cake without death or eliminating cake and being stuck there.

## Additional Information
I realize this isn't so much a bug as it is a silly thing that can happen but in hardcore packs this can be an issue. Being able to "unconnect" the nether cake from the overworld cake point could be beneficial. Please close the issue if you think it's just not worth it. Thanks!

**Comment by Mrbysco** [comment]
Implemented a way to reset the saved coordinates in the new version of TelePastries (https://minecraft.curseforge.com/projects/telepastries/files/2706079)

You could manually update or wait for Sky Factory to release an update with the new version
